name: Download and Split Large File
on: 
  workflow_dispatch: # This allows you to click "Run workflow" without a pop-up box

jobs:
  download-and-split:
    runs-on: ubuntu-latest
    env:
      # PASTE YOUR LINK INSIDE THE QUOTES BELOW
      FILE_URL: "https://ph.sf-converter.com/get?payload=UqWzaF8S3F0uxtDfUo5afyBTE3yRSL7DtAL1TgxS~j0pDl5i6T5hCeXrAz4wQa91-00mAFSA9KNjSk-fXBDlnjo1q3xYSeKZQp~PfuJPAiwP4v7TwuKG3cPwPnoHfB-D3tvr02vWZ~m6XrzpiOc0QYHux4-4a~Y1daUgT25ZUbMbrs9d3ILH0lA4GVfaOvOC0TsiHC-818caxmzj9WdmYjpr~ND~juVG4e4Z5vzX09hvrBHpnyMxv521~nRfqqgS3b7IYUwNy2kyPm8adBYg1YIOGcmfZt8hq4k5tYcxeDkUnY-32ScYHsypGaXjAk5lABlaU53AJB~WkBPwf4Ffjgj0uG3irW23RvpZEZW2-ypK2VyAYRHqY9tuiA1lcifr2jgO5uZbNCcEVmt2q7KGL8oi3jjQzWrHmUCcyX5siN0gzhr6HwcsGI36KruPfhdYhPgPgk8mJDOJjqObM2Ec3G2TMgBCejQOBNWMDDRge0I39a1LVMqPNot~fN1U8WbMKUBSb0w-lUgKA70l7XAEU5zrKw1RA4YdC~BRaoNdR4lwHNwG8~jOhW52NkBvTsCQKLMk12z1~rNWdcCtwiH6CIJghBDqgb9FAbCCoEUDa1xGIsmv-1r6w1pYuFH2U5DfzHY1ouZEURtm4lEtphhe1B__*ff27c2048fd4e4ce8877bb227be3a48f*2*1778084242"
      
    steps:
      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          # Actions runners have ~14GB SSD space; clearing this gives us more room

      - name: Download File
        run: wget -O bigfile.zip "$FILE_URL"

      - name: Split File into 500MB pieces
        run: |
          mkdir -p chunks
          split -b 500M bigfile.zip chunks/part_

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.run_number }}"
          files: chunks/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
